version: '2'
services:
  web:
    build: .
    volumes:
    - .:/pdf
    ports:
    - "5050:5000"
    depends_on:
    - sass
    - generate
  sass:
    image: ubuntudesign/sass
    volumes:
    - ./static/css/:/app
    command: sass /app/style.scss style.css
  sass_watch:
    image: ubuntudesign/sass
    volumes:
    - ./static/css/:/app
    command: sass --watch /app
  generate:
    build: .
    volumes:
    - .:/pdf
    command: python3 main.py
